### ISSUE TITLE
Entity manager not found

### ISSUE THREAD

**Issue by DanilTk** [aileftech/spring-boot-database-admin#2] opened 2023-10-01 11:17 UTC
o.s.b.SpringApplication - org.springframework.boot.SpringApplication.reportFailure : Application run failedorg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbAdmin': Resolution of declared constructors on bean Class [tech.ailef.dbadmin.external.DbAdmin] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7] failed; nested exception is java.lang.NoClassDefFoundError: jakarta/persistence/EntityManager
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors

**Comment by aileftech** [comment] 2023-10-02 06:43
I've never encountered this error before, and I'm unable to reproduce. Could you provide some more information? Also, try the latest 0.1.3 version to see maybe if it's fixed?

**Comment by aileftech** [comment] 2023-10-06 08:05
@DanilTk Hi, this could be related to #8 and already fixed #1, since it mentions the ClassLoader although the error message is different. Could you try with version 0.1.4?

**Comment by aileftech** [comment] 2023-10-28 07:59
Since this now refers to relatively very old version, this issue has probably been fixed. I'm closing this for now, but I will examine again in case of new feedbacks.

**Closed by aileftech** 2023-10-28 07:59 UTC
Labels: bug
